// <auto-generated />
namespace Unidad3.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Arreglo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Arreglo));
        
        string IMigrationMetadata.Id
        {
            get { return "202012180009245_Arreglo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
