// <auto-generated />
namespace Unidad3.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StartProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StartProject));
        
        string IMigrationMetadata.Id
        {
            get { return "202011242240395_StartProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
